### ISSUE TITLE
LockRegistry never returns Optional#empty

### ISSUE THREAD

**Issue by Riggs333** [yusufaytas/dlock#1]
Hi,
thanks for providing this library.

Looking at the source I wonder why the methods in `com.yusufaytas.dlock.core.LockRegistry` (`setLock` and `getLock`) have `Optional` as return type.

If `setLock` is never called then the call to `getLock` will throw a `NullPointerException`:

```java
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at com.yusufaytas.dlock.core.LockRegistry.getLock(LockRegistry.java:37)
```

**Comment by yusufaytas** [comment]
Hi,

Good catch, I've pushed [a fix](https://github.com/yusufaytas/dlock/commit/70184b30e7e398f3ff90970a1d6056f5045f97f1) for this. 

Thanks,
